name: Build Windows Executable

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --name "CertiFier" --add-data "database.db;." --add-data "uploads;uploads" main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CertiFier-Windows
        path: dist/CertiFier.exe